/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Manga Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface Manga {
  id: number;
  title: string;
  status: string;
  chapters_read: number;
}
