/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Manga Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateManga {
  title?: string | null;
  status?: string | null;
  chapters_read?: number | null;
}
