/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Manga Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AddManga,
  Manga,
  UpdateManga
} from './model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class MangaTrackerAPIService {
  private readonly http = inject(HttpClient);
/**
 * @summary List Manga
 */
 listMangaApiMangaGet<TData = Manga[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listMangaApiMangaGet<TData = Manga[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listMangaApiMangaGet<TData = Manga[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listMangaApiMangaGet<TData = Manga[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/manga`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/manga`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/manga`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * @summary Add Manga
 */
 addMangaApiMangaPost<TData = Manga>(addManga: AddManga, options?: HttpClientBodyOptions): Observable<TData>;
 addMangaApiMangaPost<TData = Manga>(addManga: AddManga, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 addMangaApiMangaPost<TData = Manga>(addManga: AddManga, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  addMangaApiMangaPost<TData = Manga>(
    addManga: AddManga, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/manga`,
      addManga,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/manga`,
      addManga,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/manga`,
      addManga,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * @summary Get Manga
 */
 getMangaApiMangaMangaIdGet<TData = Manga>(mangaId: number, options?: HttpClientBodyOptions): Observable<TData>;
 getMangaApiMangaMangaIdGet<TData = Manga>(mangaId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getMangaApiMangaMangaIdGet<TData = Manga>(mangaId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getMangaApiMangaMangaIdGet<TData = Manga>(
    mangaId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/manga/${mangaId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/manga/${mangaId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/manga/${mangaId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * @summary Update Manga
 */
 updateMangaApiMangaMangaIdPatch<TData = Manga>(mangaId: number,
    updateManga: UpdateManga, options?: HttpClientBodyOptions): Observable<TData>;
 updateMangaApiMangaMangaIdPatch<TData = Manga>(mangaId: number,
    updateManga: UpdateManga, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateMangaApiMangaMangaIdPatch<TData = Manga>(mangaId: number,
    updateManga: UpdateManga, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateMangaApiMangaMangaIdPatch<TData = Manga>(
    mangaId: number,
    updateManga: UpdateManga, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/manga/${mangaId}`,
      updateManga,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/manga/${mangaId}`,
      updateManga,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/manga/${mangaId}`,
      updateManga,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * @summary Delete Manga
 */
 deleteMangaApiMangaMangaIdDelete<TData = void>(mangaId: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteMangaApiMangaMangaIdDelete<TData = void>(mangaId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteMangaApiMangaMangaIdDelete<TData = void>(mangaId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteMangaApiMangaMangaIdDelete<TData = void>(
    mangaId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/manga/${mangaId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/manga/${mangaId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/manga/${mangaId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

};

